export const TEMPLATES = [
  { name: 'Analyse de document', category: 'Analyse', description: 'Analyse approfondie avec extraction structurée', prompt: 'Tu es un analyste expert. Analyse le document suivant avec rigueur.\n\n<document>\n[INSÉRER LE DOCUMENT ICI]\n</document>\n\n## 1. Résumé exécutif\n## 2. Points clés (5-7)\n## 3. Informations critiques\n## 4. Questions ouvertes\n## 5. Recommandations\n\nSois précis, factuel et concis.' },
  { name: 'Résumé exécutif', category: 'Rédaction', description: 'Transformer un document long en résumé professionnel', prompt: 'Tu es un expert en communication professionnelle. Crée un résumé exécutif du texte ci-dessous.\n\n<texte_source>\n[INSÉRER LE TEXTE ICI]\n</texte_source>\n\n<contraintes>\n- 150-200 mots maximum\n- Ton professionnel et factuel\n- Structure : contexte → enjeux → résultats → implications\n- Public : dirigeants sans temps pour lire le document complet\n</contraintes>\n\nCommence directement par le résumé.' },
  { name: 'Code Python', category: 'Code', description: 'Générer du code Python propre et documenté', prompt: 'Tu es un développeur Python senior. Écris un code Python pour :\n\n<tache>\n[DÉCRIRE LA TÂCHE]\n</tache>\n\n<exigences>\n- Python 3.10+, PEP 8\n- Type hints sur toutes les fonctions\n- Gestion des erreurs try/except\n- Docstrings concises\n- Exemple d\'utilisation à la fin\n</exigences>\n\nExplique brièvement les choix techniques importants.' },
  { name: 'Email professionnel', category: 'Rédaction', description: 'Rédiger des emails clairs et percutants', prompt: 'Tu es un expert en communication professionnelle.\n\n<contexte>\nExpéditeur : [TON RÔLE]\nDestinataire : [RÔLE DU DESTINATAIRE]\nObjectif : [CE QUE TU VEUX OBTENIR]\nTon : [Formel / Semi-formel]\n</contexte>\n\n<contenu>\n[INFORMATIONS À TRANSMETTRE]\n</contenu>\n\nRédige un email avec objet accrocheur, corps structuré (contexte → message → appel à l\'action), formule de politesse. Maximum 200 mots.' },
  { name: 'Extraction JSON', category: 'Extraction', description: 'Extraire des données structurées depuis du texte', prompt: 'Tu es un expert en extraction d\'informations.\n\nExtrait les informations du texte ci-dessous et retourne-les en JSON valide.\n\n<schema>\n{\n  "champ1": "description",\n  "champ2": "description"\n}\n</schema>\n\n<texte>\n[INSÉRER LE TEXTE]\n</texte>\n\nRègles : JSON uniquement, null si absent, dates en ISO 8601.' },
  { name: 'Analyse SWOT', category: 'Analyse', description: 'Analyse stratégique Forces/Faiblesses/Opportunités/Menaces', prompt: 'Tu es un consultant en stratégie senior.\n\nRéalise une analyse SWOT pour :\n<sujet>[ENTREPRISE / PRODUIT / PROJET]</sujet>\n\n<contexte>[INFORMATIONS DISPONIBLES]</contexte>\n\nPour chaque quadrant : 4-6 points concrets et actionnables.\nConclus avec 3 recommandations stratégiques prioritaires.' },
  { name: 'Plan de projet', category: 'Planification', description: 'Plan de projet structuré avec jalons et livrables', prompt: 'Tu es un chef de projet expérimenté (PMP).\n\n<projet>\nNom : [NOM]\nObjectif : [OBJECTIF]\nDurée : [DURÉE]\nÉquipe : [COMPOSITION]\nContraintes : [BUDGET, RESSOURCES]\n</projet>\n\nInclure : phases avec dates, jalons clés, livrables, risques et mitigation, KPIs de succès.\nFormat : tableau markdown par phase.' },
  { name: 'Réponse client difficile', category: 'Service Client', description: 'Gérer des situations clients complexes avec empathie', prompt: 'Tu es un expert en relation client.\n\n<message_client>\n[COLLER LE MESSAGE]\n</message_client>\n\n<contexte>\nSituation : [CONTEXTE]\nSolutions disponibles : [OPTIONS]\nLimites : [CE QU\'ON NE PEUT PAS FAIRE]\n</contexte>\n\nRéponse : empathique, factuelle, solution concrète, 100-150 mots.' },
  { name: 'Article SEO', category: 'Rédaction', description: 'Article de blog optimisé pour le référencement', prompt: 'Tu es un rédacteur web expert en SEO.\n\n<parametres>\nSujet : [SUJET]\nMot-clé : [MOT-CLÉ PRINCIPAL]\nPublic : [AUDIENCE]\nLongueur : [MOTS]\n</parametres>\n\nStructure : titre H1 (<60 car.), intro avec hook, 3-5 sections H2, paragraphes courts, conclusion + CTA, méta-description (150-160 car.).\nIntègre le mot-clé 3-5 fois naturellement.' },
  { name: 'Audit de code', category: 'Code', description: 'Réviser et améliorer un code existant', prompt: 'Tu es un architecte logiciel senior.\n\n```\n[COLLER LE CODE]\n```\n\nAnalyse :\n1. **Bugs potentiels** (CRITIQUE/MAJEUR/MINEUR)\n2. **Performance** (optimisations)\n3. **Sécurité** (vulnérabilités)\n4. **Maintenabilité** (lisibilité, nommage)\n5. **Bonnes pratiques** (SOLID, DRY)\n\nPour chaque problème : sévérité + code corrigé.' },
  { name: 'Synthèse de recherche', category: 'Recherche', description: 'Synthétiser plusieurs sources en document cohérent', prompt: 'Tu es un chercheur et analyste expert.\n\n<sources>\n[SOURCE 1] : ...\n[SOURCE 2] : ...\n</sources>\n\n<question_directrice>\n[PROBLÉMATIQUE À ADRESSER]\n</question_directrice>\n\nSynthèse : convergences, divergences, conclusions principales, fiabilité des sources.\n400-600 mots avec références [SOURCE X].' },
  { name: 'Classification de textes', category: 'Classification', description: 'Classifier automatiquement des textes', prompt: 'Tu es un expert en classification.\n\n<categories>\n[CAT_1] : description\n[CAT_2] : description\n</categories>\n\n<texte>\n[INSÉRER LE TEXTE]\n</texte>\n\nRéponds uniquement en JSON :\n{\n  "categorie": "NOM",\n  "confiance": 0.0-1.0,\n  "justification": "1-2 phrases"\n}' },
  { name: 'FAQ depuis contenu', category: 'Rédaction', description: 'Générer des FAQ pertinentes depuis un contenu', prompt: 'Tu es un expert en communication et UX.\n\n<contenu_source>\n[INSÉRER LE CONTENU]\n</contenu_source>\n\n<public>[DÉCRIRE LE PUBLIC]</public>\n\n8-12 questions formulées comme l\'utilisateur, réponses de 2-4 phrases.\nFormat :\n**Q : [Question ?]**\nR : [Réponse concise.]' },
  { name: 'System prompt chatbot', category: 'Chatbot', description: 'Créer un prompt système pour assistant IA spécialisé', prompt: 'Crée un prompt système complet pour :\n\n<profil>\nNom : [NOM]\nDomaine : [DOMAINE]\nEntreprise : [CONTEXTE]\nPublic : [UTILISATEURS]\nTon : [FORMEL/AMICAL]\n</profil>\n\n<capacites>\nPeut faire : [LISTE]\nNe peut pas faire : [LIMITES]\n</capacites>\n\nDéfinis : identité, comportement, limites, format des réponses, gestion des hors-sujet.' },
  { name: 'Traduction adaptée', category: 'Traduction', description: 'Traduire en adaptant au contexte culturel', prompt: 'Tu es un traducteur professionnel expert.\n\n<texte>\n[INSÉRER LE TEXTE]\n</texte>\n\n<parametres>\nSource : [LANGUE]\nCible : [LANGUE]\nDomaine : [Juridique/Technique/Marketing]\nTon : [Formel/Informel]\nPublic : [PAYS/RÉGION]\n</parametres>\n\nFournis : 1) La traduction adaptée culturellement, 2) Termes techniques conservés avec explication, 3) Notes de traducteur sur les choix significatifs.' }
]
